/*
 * Copyright (c) 2022 Takamaru. All rights reserved.
 */

#ifndef TAKAMRCPP_LIBS_DATETIME_INCLUDE_DATETIME_LEAP_YEAR_H_
#define TAKAMRCPP_LIBS_DATETIME_INCLUDE_DATETIME_LEAP_YEAR_H_

bool isLeapYear(double year);

#endif  // TAKAMRCPP_LIBS_DATETIME_INCLUDE_DATETIME_LEAP_YEAR_H_
